name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Hello @${{ github.actor }}, thank you for submitting a PR to SMIT! To allow your work to be integrated as seamlessly as possible, we advise you to:

            - ✅ Verify your PR is **up-to-date** with `Thytu/SMIT` `master` branch. If your PR is behind you can update your code by clicking the 'Update branch' button or by running `git pull` and `git merge master` locally.
            - ✅ Verify that you added a descriptive title and a clear summary of the changes made in your pull request.
            - ✅ Ensure all new code is adequately documented and commented for clarity and future reference.
            - ✅ Confirm that any related issues or tickets are referenced in the pull request description for tracking purposes.

          issue-message: |
            👋 Hello @${{ github.actor }}, thank you for your interest in SMIT 🚀!

            If this is a 🐛 Bug Report, please provide a **minimum reproducible example** to help us debug it.

            If this is a 💡 Feature Request, please provide a clear outline of the functionality and its use cases.
